apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goflow-kube-kafka-reader
  name: goflow-kube-kafka-reader
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goflow-kube-kafka-reader
  template:
    metadata:
      labels:
        app: goflow-kube-kafka-reader
    spec:
      volumes:
        - name: config-vol
          configMap:
            name: goflow-kube-kafka-reader-config
      containers:
        - command:
            - /bin/sh
            - -c
            - /goflow-kube -loglevel "trace" -config /etc/goflow-kube-kafka-reader/config.yaml
          image: quay.io/netobserv/goflow2-kube:main
          imagePullPolicy: IfNotPresent
          name: goflow-kube-kafka-reader
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          volumeMounts:
              - mountPath: /etc/goflow-kube-kafka-reader
                name: config-vol
      serviceAccountName: goflow-kube-kafka-reader
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: goflow-kube-kafka-reader-config
data:
  config.yaml: |
    listen: http://my-cluster-kafka-bootstrap.default.svc.cluster.local:9092
    kafka:
      tls: false
      topic: goflow-kube
      reader:
        groupID: goflow-kube
    loki:
      labels:
        - SrcNamespace
        - SrcWorkload
        - DstNamespace
        - DstWorkload
      ignoreList:
        - NextHop
        - NextHopAS
    printOutput: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: goflow-kube-kafka-reader
  name: goflow-kube-kafka-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: goflow-kube-kafka-reader
  name: goflow-kube-kafka-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: goflow-kube-kafka-reader
subjects:
  - kind: ServiceAccount
    name: goflow-kube-kafka-reader
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: goflow-kube-kafka-reader
  name: goflow-kube-kafka-reader
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - pods
      - replicasets
      - services
    verbs:
      - list
      - get
      - watch

